package model;
// Generated 25-abr-2018 16:42:23 by Hibernate Tools 4.3.1



/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private int idProfesor;
     private String nombre;
     private String ape1;
    // private String apellido2;
     private Direcion direc;

    public Profesor() {
    }

    public Profesor(int idProfesor, String nombre, String ape1, Direcion direc) {
       this.idProfesor = idProfesor;
       this.nombre = nombre;
       this.ape1 = ape1;
     //  this.apellido2 = apellido2;
       this.direc = direc;
    }
   
    public int getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(int idProfesor) {
        this.idProfesor = idProfesor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.ape1;
    }
    
    public void setApellido1(String apellido1) {
        this.ape1 = apellido1;
    }
 

    public Direcion getDirec() {
        return direc;
    }

    public void setDirec(Direcion direc) {
        this.direc = direc;
    }


}


