package model;
// Generated 27-abr-2018 7:58:15 by Hibernate Tools 4.3.1



/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private int idDireccion;
     private String calle;
     private int numero;
     private String poblacion;
     private String provincia;

    public Direccion() {
    }

    public Direccion(int idDireccion, String calle, int numero, String poblacion, String provincia) {
       this.idDireccion = idDireccion;
       this.calle = calle;
       this.numero = numero;
       this.poblacion = poblacion;
       this.provincia = provincia;
    }
   
    public int getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(int idDireccion) {
        this.idDireccion = idDireccion;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }




}


