package model;
// Generated 27-abr-2018 7:58:15 by Hibernate Tools 4.3.1



/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private int idProfesor;
     private String nombre;
     private String ape1;

    public Profesor() {
    }

    public Profesor(int idProfesor, String nombre, String ape1) {
       this.idProfesor = idProfesor;
       this.nombre = nombre;
       this.ape1 = ape1;
    }
   
    public int getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(int idProfesor) {
        this.idProfesor = idProfesor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApe1() {
        return this.ape1;
    }
    
    public void setApe1(String ape1) {
        this.ape1 = ape1;
    }




}


