package modelo;
// Generated 29-abr-2018 1:28:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personaje generated by hbm2java
 */
public class Personaje implements java.io.Serializable {

    private Integer id;
    private String nombre;
    private String alias;

    private Set<Pelicula> peliculas = new HashSet<Pelicula>(0);

    public Personaje() {
    }

    public Personaje(String nombre, String alias) {
        this.nombre = nombre;
        this.alias = alias;

    }

    @Override
    public String toString() {
        return "Personaje{" + "id=" + id + ", nombre=" + nombre + ", alias=" + alias + ", peliculas=" + peliculas + '}';
    }

    public Personaje(String nombre, String alias, Set<Pelicula> peliculas) {
        this.nombre = nombre;
        this.alias = alias;

        this.peliculas = peliculas;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public Set<Pelicula> getPeliculas() {
        return peliculas;
    }

    public void setPeliculas(Set<Pelicula> peliculas) {
        this.peliculas = peliculas;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
