package model;
// Generated 18-abr-2018 16:27:51 by Hibernate Tools 4.3.1



/**
 * TUsuaris generated by hbm2java
 */
public class TUsuaris  implements java.io.Serializable {


     private int id;
     private String password;
     private String nom;

    public TUsuaris() {
    }

    public TUsuaris(int id, String password, String nom) {
       this.id = id;
       this.password = password;
       this.nom = nom;
    }

//    @Override
//    public String toString() {
//        return "TUsuaris{" + "id=" + id + ", password=" + password + ", nom=" + nom + '}';
//    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }




}


